In [5]:
import pandas as pd
df = pd.read_csv("../data/Home_Guards_Strength_As_On-October_2022.csv")
#print(df.head())
# print(df.shape)
# print(df.dtypes)
# print(df.isnull().sum())
print(df)

    SL. NO. NAME OF THE DISTRICT  NUMBER  OF UNITS  ALLOTTED STRENGTH  \
0         1      Bengaluru North                18               1850
1         2      Bengaluru Rural                15               1650
2         3      Bengaluru South                15               1850
3         4            Bagalkote                23               1000
4         5             Belagavi                30               1350
5         6              Ballari                22               1500
6         7                Bidar                15               1000
7         8        Chikkmagaluru                20                800
8         9       Chamarajanagar                 9                700
9        10         Chithradurga                14                700
10       11      Chikkaballapura                 7                700
11       12              Dharwad                 8                800
12       13           Davanagere                14                651
13       14     Dakshina Kannada                15               1000
14       15                Gadag                11                700
15       16            Kalaburgi                 9               1000
16       17               Hassan                30               1200
17       18               Haveri                 8                700
18       19               Kodagu                 9                500
19       20                Kolar                10               1200
20       21               Koppal                14                700
21       22               Mandya                12                949
22       23               Mysore                13               1300
23       24              Raichur                11                800
24       25            Ramanagar                 9                700
25       26           Shivamogga                15               1000
26       27             Tumakuru                18                900
27       28                Udupi                 8                500
28       29       Uttara Kannada                15                900
29       30           Vijayapura                12                800
30       31             Yadagiri                 7                600

    NO. OF HOME GUARDS(men)  NO. OF HOME GUARDS(women)  ACTUAL STRENGTH  \
0                       832                        782             1614
1                       846                        411             1257
2                      1136                        709             1845
3                       889                         96              985
4                      1234                         61             1295
5                      1377                        100             1477
6                       852                        125              977
7                       484                         52              536
8                       633                         60              693
9                       566                         55              621
10                      448                         91              539
11                      490                        136              626
12                      568                         62              630
13                      610                        246              856
14                      648                          0              648
15                      904                         87              991
16                     1063                         69             1132
17                      498                         51              549
18                      193                         59              252
19                      755                        133              888
20                      634                         61              695
21                      652                         54              706
22                      931                        151             1082
23                      726                         33              759
24                      383                        134              517
25                      661                         72              733
26                      619                         91              710
27                      366                         63              429
28                      579                         76              655
29                      687                         51              738
30                      480                          0              480

    VACANCY
0       236
1       393
2         5
3        15
4        55
5        23
6        23
7       264
8         7
9        79
10      161
11      174
12       21
13      144
14       52
15        9
16       68
17      151
18      248
19      312
20        5
21      243
22      218
23       41
24      183
25      267
26      190
27       71
28      245
29       62
30      120